#!/usr/bin/env python3

import subprocess
import sys

def main():
    if len(sys.argv) != 2:
        print("Enter a command: ./run <command>")
        sys.exit(1)
    
    argument = sys.argv[1]
    command = ["node", "./cli/dist/run.js", argument]
    
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()